"""All constant used in project api response messages."""
USER_ADDED = "user_added"
USER_ALREADY_EXIST = "user_already_exist"
USER_UPDATED = "user_added"
USER_EMAIL_VERIFIED = "user_email_verified"
USER_ACTIVE = "user_active"
REFRESH_TOKEN = "refresh_token"
LOGIN_OTP_SEND_ON_MAIL = "Enter otp recieved on mail."
