"""All column name for user table."""
user_email = "email"
secret_key = "secret_key"
trashed_time = "trashed_date_time"
otp_generation_time = "otp_generation_time"
name = "name"
about = "about"
secret_key = "secret_key"
verification_token = "verification_token"
password_otp = "p-otp"
login_otp = "l-otp"
role = "role"
# trashed_time = "trashed_date_time"
